server:
  port: 8092
spring:
  application:
    name: edu-front-boot
  main:
    allow-bean-definition-overriding: true
  oauth:
    client_id: test_client
    client_secret: test_secret
    scope: read
    grant_type: password
    refresh_grant_type: refresh_token
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@