server:
  port: 8088

feign:
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html, application/xml, application/json # 设置压缩的数据类型，此处也是默认值
      min-request-size: 2048
    response:
      enabled: true
#  hystrix:
#    enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: edu-order-boot
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///edu_order?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "!andreaszhou"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: edu-config-boot
      profile: "dev"
      name: ${spring.application.name}
#ribbon:
#  ConnectTimeout: 2000
#  ReadTimeout: 5000
#  okToRetryOnAllOperations: true
#  maxAutoRetries: 0
#  maxAutoRetriesNextServer: 0
#  NFLoadBalancerRuleClassName: com.netfilx.loadbalancer.RoundRobinRule
#  eureka:
#    enabled: true