spring:
  application:
    name: edu-course-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///edu_course?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "!andreaszhou"
  main:
    allow-bean-definition-overriding: true
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除 默认90s
    lease-expiration-duration-in-seconds: 9
    #服务刷新时间配置，每隔这个时间会主动心跳一次 默认30s
    lease-renewal-interval-in-seconds: 3