server:
  port: 9001
spring:
  application:
    name: edu-gateway-boot
  cloud:
    gateway:
      routes:
        - id: lagou-edu-front
          uri: lb://edu-front-boot
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
        - id: lagou-edu-boss
          uri: lb://edu-boss-boot
          predicates:
            - Path=/boss/**
          filters:
            - StripPrefix=1
        - id: lagou-edu-bom
          uri: lb://edu-bom-boot
          predicates:
            - Path=/bom/**
          filters:
            - StripPrefix=1
#    config:
#      discovery:
#        service-id: edu-config-boot
#        enabled: true
#      label: main
#      profile: dev
#      name: ${spring.application.name}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@

# 网关白名单，无需要鉴权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs,/user/login,/course,/ad,/pay,/doc.html,/webjars,/swagger,/pay/wxCallback,/pay/zfbCallback,/user/vfcode,/user/refresh_token,/weixin,/comment,/permission/getUserPermissions